version: '3.8'  # Docker Compose 버전

services:
  # 1) config-service
  config-service:
    image: config-service:1.0
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - encrypt.key-store.location=file:/apiEncryptionKey.jks
    networks:
      - ecommerce-network

  # 2) service-discovery
  service-discovery:
    image: service-discovery:1.0
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network

  # 3) apigateway-service
  apigateway-service:
    image: apigateway-service:1.0
    container_name: apigateway-service
    ports:
      - "8000:8000"
    networks:
      - ecommerce-network

  # 4) mariadb-server
  mariadb-server:
    image: mariadb:latest
    container_name: mariadb-server
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=test1357
    networks:
      - ecommerce-network

  # 5) broker (Kafka)
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - ecommerce-network

  # 6) mysql (Zipkin용)
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASSWORD=zipkin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network

  # 7) zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_DB=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_HOST=mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
